#!/usr/bin/env python3
import os
from pathlib import Path

for d in ["core", "agents", "data/ohlcv", "pine", "tests", "logs"]:
    Path(d).mkdir(parents=True, exist_ok=True)

FILES = {
"requirements.txt": "ccxt>=4.1.0\npandas>=2.1.0\nnumpy>=1.26.0\npyarrow>=14.0.0\nlanggraph>=0.2.0\nlangchain-ollama>=0.2.0\npydantic>=2.9.0\ninstructor>=1.4.0\nvectorbt>=0.26.0\nfastapi>=0.115.0\nuvicorn>=0.30.0\npytest>=7.4.0\npython-dotenv>=1.0.0\n",

"core/config.py": "import os\nfrom pathlib import Path\nfrom dotenv import load_dotenv\n\nload_dotenv()\nBASE_DIR = Path(__file__).parent.parent\nDATA_DIR = BASE_DIR / 'data' / 'ohlcv'\nLOGS_DIR = BASE_DIR / 'logs'\nOLLAMA_HOST = os.getenv('OLLAMA_HOST', 'http://localhost:11434')\nFASTAPI_PORT = int(os.getenv('FASTAPI_PORT', '8000'))\nTIMEFRAMES = ['1m', '5m', '15m', '30m', '1h', '4h', '12h']\nSYMBOL = 'BTC/USDT'\nDEFAULT_THESIS = 'Compra quando velocidade de alta supera 0.8 com inercia >= 5 candles e saldo de pressao positivo.'\n",

"core/physics.py": "import pandas as pd\nimport numpy as np\n\ndef calcular_velocidade(df):\n    df = df.copy()\n    dt_seconds = (df.index[1] - df.index[0]).total_seconds()\n    df['price_change'] = df['close'].diff()\n    df['velocity'] = df['price_change'] / dt_seconds\n    return df\n\ndef calcular_inercia(df):\n    df = df.copy()\n    direction = np.sign(df['close'].diff())\n    df['inertia'] = direction.groupby((direction != direction.shift()).cumsum()).cumcount() + 1\n    return df\n\ndef calcular_vetor_ataque(df, window):\n    df = df.copy()\n    df['is_bull'] = df['velocity'] > 0\n    df['attack_bull'] = df.loc[df['is_bull'], 'velocity'].rolling(window, min_periods=1).sum()\n    df['attack_bear'] = df.loc[~df['is_bull'], 'velocity'].rolling(window, min_periods=1).sum().abs()\n    df['attack_bull'] = df['attack_bull'].fillna(0)\n    df['attack_bear'] = df['attack_bear'].fillna(0)\n    return df\n\ndef calcular_saldo_pressao(df):\n    df = df.copy()\n    df['pressure_balance'] = df['attack_bull'] - df['attack_bear']\n    return df\n\ndef pipeline_fisica(df):\n    df = calcular_velocidade(df)\n    df = calcular_inercia(df)\n    for w in [5, 15, 60, 240, 720]:\n        df = calcular_vetor_ataque(df, w)\n    return calcular_saldo_pressao(df)\n",

"core/theses.py": "import pandas as pd\nimport numpy as np\n\ndef tese_inercia_critica(df, v_thresh=0.8, min_inertia=5):\n    sig = (df['velocity'].abs() > v_thresh) & (df['inertia'] >= min_inertia)\n    if not sig.any(): return {'n_sinais': 0, 'win_rate': 0.0}\n    next_dir = np.sign(df['close'].diff().shift(-1))\n    curr_dir = np.sign(df['velocity'])\n    wins = (next_dir == curr_dir)[sig].sum()\n    total = sig.sum()\n    return {'n_sinais': int(total), 'win_rate': round(wins/total, 3)}\n\ndef tese_exaustao_vetor(df, peak_lookback=10):\n    df = df.copy()\n    df['vel_abs'] = df['velocity'].abs()\n    df['is_peak'] = df['vel_abs'] == df['vel_abs'].rolling(peak_lookback).max()\n    df['decel'] = df['velocity'].diff() < 0\n    df['opp_acc'] = -df['velocity'].diff().shift(1) > 0\n    sig = df['is_peak'] & df['decel'] & df['opp_acc']\n    if not sig.any(): return {'n_sinais': 0, 'reversal_rate': 0.0}\n    next_rev = (np.sign(df['close'].diff().shift(-1)) != np.sign(df['velocity'].shift(-1)))[sig].sum()\n    return {'n_sinais': int(sig.sum()), 'reversal_rate': round(next_rev/sig.sum(), 3)}\n\ndef tese_dominio_fluxo(df, squeeze_lookback=20):\n    df = df.copy()\n    df['pressure_extreme'] = df['pressure_balance'].abs() > df['pressure_balance'].rolling(squeeze_lookback).std() * 2\n    df['vol_surge'] = df['volume'] > df['volume'].rolling(squeeze_lookback).mean() * 1.5\n    df['range_break'] = (df['close'] - df['close'].shift(squeeze_lookback)).abs() > df['close'].rolling(squeeze_lookback).std() * 1.5\n    sig = df['pressure_extreme'].shift(1)\n    wins = (df['vol_surge'] & df['range_break'])[sig].sum()\n    total = sig.sum()\n    return {'n_sinais': int(total), 'squeeze_accuracy': round(wins/total, 3) if total > 0 else 0.0}\n",

"agents/sdd_spec.py": "from pydantic import BaseModel, Field\nfrom langchain_ollama import ChatOllama\nimport instructor\nimport os\n\nclass TradingSpec(BaseModel):\n    asset: str = Field(description='Ativo analisado')\n    timeframe: str = Field(description='Timeframe principal')\n    entry_logic: str = Field(description='Logica de entrada baseada em velocidade/inercia')\n    exit_logic: str = Field(description='Logica de saida')\n    risk_pct: float = Field(ge=0.1, le=5.0)\n    pine_webhook_format: str = Field(description='JSON esperado do webhook')\n\ndef generate_spec(thesis):\n    client = instructor.from_llm(\n        ChatOllama(model='qwen2.5:7b', temperature=0.2, base_url=os.getenv('OLLAMA_HOST', 'http://localhost:11434'))\n    )\n    return client.chat.completions.create(\n        model='qwen2.5:7b',\n        response_model=TradingSpec,\n        messages=[{'role': 'user', 'content': f'Transforme a tese em spec estruturada:\\n{thesis}'}]\n    )\n",

"agents/vibe_coder.py": "from langchain_ollama import ChatOllama\nimport instructor\nimport os\n\ndef generate_code(spec):\n    client = instructor.from_llm(\n        ChatOllama(model='qwen2.5-coder:7b', temperature=0.1, base_url=os.getenv('OLLAMA_HOST', 'http://localhost:11434'))\n    )\n    prompt = f'Gere APENAS codigo Python valido para backtest vectorbt com esta spec:\\n{spec}\\nRegras: use pandas+vectorbt, funcoes load_data, run_backtest, evaluate_metrics. Sem explicacoes.'\n    response = client.chat.completions.create(\n        model='qwen2.5-coder:7b',\n        response_model=str,\n        messages=[{'role': 'user', 'content': prompt}]\n    )\n    return response.strip('```python').strip('```')\n",

"agents/validator.py": "import subprocess, sys\ndef run_tests():\n    result = subprocess.run([sys.executable, '-m', 'pytest', 'tests/', '-v', '--tb=short'], capture_output=True, text=True)\n    return {'success': result.returncode == 0, 'stdout': result.stdout, 'stderr': result.stderr}\n",

"agents/graph.py": "from langgraph.graph import StateGraph, END\nfrom typing import TypedDict, Optional\nfrom .sdd_spec import generate_spec\nfrom .vibe_coder import generate_code\nfrom .validator import run_tests\nimport json\nfrom pathlib import Path\n\nclass RnDState(TypedDict):\n    thesis: str\n    spec: Optional[dict]\n    code: Optional[str]\n    test_result: Optional[dict]\n    status: str\n\ndef sdd_node(state):\n    spec = generate_spec(state['thesis'])\n    state['spec'] = spec.model_dump()\n    state['status'] = 'spec_ready'\n    return state\n\ndef vibe_node(state):\n    code = generate_code(json.dumps(state['spec'], indent=2))\n    Path('generated_strategy.py').write_text(code)\n    state['code'] = code\n    state['status'] = 'coded'\n    return state\n\ndef validate_node(state):\n    state['test_result'] = run_tests()\n    state['status'] = 'validated' if state['test_result']['success'] else 'failed'\n    return state\n\ndef build_graph():\n    workflow = StateGraph(RnDState)\n    workflow.add_node('sdd', sdd_node)\n    workflow.add_node('vibe', vibe_node)\n    workflow.add_node('validate', validate_node)\n    workflow.set_entry_point('sdd')\n    workflow.add_edge('sdd', 'vibe')\n    workflow.add_edge('vibe', 'validate')\n    workflow.add_edge('validate', END)\n    return workflow.compile()\n",

"data/fetch_btc.py": "import ccxt, pandas as pd, time\nfrom pathlib import Path\n\nEXCHANGE = 'binance'\nSYMBOL = 'BTC/USDT'\nTIMEFRAMES = ['1m','5m','15m','30m','1h','4h','12h']\nDATA_DIR = Path('data/ohlcv')\nDATA_DIR.mkdir(parents=True, exist_ok=True)\nexchange = ccxt.binance({'enableRateLimit': True})\n\nfor tf in TIMEFRAMES:\n    file = DATA_DIR / f\"{SYMBOL.replace('/', '_')}_{tf}.parquet\"\n    if file.exists():\n        print(f'✅ {tf} ja existe')\n        continue\n    print(f'📥 Baixando {tf}...')\n    since = exchange.parse8601('2020-01-01T00:00:00Z')\n    all_candles = []\n    while True:\n        ohlcv = exchange.fetch_ohlcv(SYMBOL, tf, since=since, limit=1000)\n        if not ohlcv: break\n        all_candles.extend(ohlcv)\n        since = ohlcv[-1][0] + 1\n        time.sleep(0.3)\n    df = pd.DataFrame(all_candles, columns=['timestamp','open','high','low','close','volume'])\n    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')\n    df.set_index('timestamp', inplace=True)\n    df.to_parquet(file, engine='pyarrow')\n    print(f'💾 Salvo {file} ({len(df)} candles)')\n",

"pine/velocimetro_sensor.pine": "//@version=5\nindicator('Velocimetro de Fluxo e Vetores', overlay=false, precision=4)\nlen_velocity = input.int(14, 'Janela Velocidade')\nlen_inertia  = input.int(5,  'Inercia Minima')\nlen_pressure = input.int(20, 'Saldo de Pressao (candles)')\n\ndt = timeframe.in_seconds\nvel = (close - close[1]) / dt\ndir = ta.sgn(vel)\n\ninertia = 0.0\nfor i = 1 to len_inertia\n    if dir == dir[i]\n        inertia += 1\n    else\n        break\n\nbull_vec = 0.0\nbear_vec = 0.0\nfor i = 0 to len_velocity - 1\n    v = vel[i]\n    if v > 0 then bull_vec += v\n    else bear_vec += math.abs(v)\n\npressure = bull_vec - bear_vec\n\nplot(vel, 'Velocidade', color=vel >= 0 ? color.green : color.red, linewidth=2)\nplot(bull_vec, 'Vetor Alta', color=color.green, transp=50)\nplot(bear_vec, 'Vetor Baixa', color=color.red, transp=50)\nplot(pressure, 'Saldo de Pressao', color=pressure >= 0 ? color.blue : color.purple, linewidth=3)\n\ncond_inertia = inertia >= len_inertia and math.abs(vel) > ta.avg(ta.abs(vel), len_velocity) * 1.5\nalertcondition(cond_inertia, 'Inercia_Critica', '{\"tese\":\"inercia\",\"dir\":\"' + (vel>0?'long':'short') + '\"}')\n\ncond_exaustao = vel > 0 and vel < vel[1] and -vel[1] > 0\nalertcondition(cond_exaustao, 'Exaustao_Vetor', '{\"tese\":\"exaustao\",\"dir\":\"short\"}')\n\ncond_pressao = math.abs(pressure) > ta.stdev(pressure, len_pressure) * 2\nalertcondition(cond_pressao, 'Dominio_Fluxo', '{\"tese\":\"dominio\",\"saldo\":\"' + str.tostring(pressure) + '\"}')\n",

"tests/test_physics_and_theses.py": "import pandas as pd\nimport numpy as np\nfrom core.physics import pipeline_fisica\nfrom core.theses import tese_inercia_critica, tese_exaustao_vetor, tese_dominio_fluxo\nfrom pathlib import Path\nimport pytest\n\ndef load_test_data():\n    f = Path('data/ohlcv/BTC_USDT_15m.parquet')\n    if not f.exists():\n        pytest.skip('Dados nao baixados. Rode python data/fetch_btc.py primeiro.')\n    return pd.read_parquet(f)\n\ndef test_physics_pipeline():\n    df = load_test_data()\n    out = pipeline_fisica(df)\n    assert 'velocity' in out.columns\n    assert 'inertia' in out.columns\n    assert 'pressure_balance' in out.columns\n    assert len(out) == len(df)\n\ndef test_theses_execution():\n    df = load_test_data()\n    df = pipeline_fisica(df)\n    assert 'n_sinais' in tese_inercia_critica(df)\n    assert 'reversal_rate' in tese_exaustao_vetor(df)\n    assert 'squeeze_accuracy' in tese_dominio_fluxo(df)\n",

"main.py": "from fastapi import FastAPI, Request\nimport logging, json\nfrom datetime import datetime\nimport uvicorn\nfrom core.config import FASTAPI_PORT\n\napp = FastAPI(title='Projeto Genesis - Velocimetro de Fluxo')\nlogging.basicConfig(level=logging.INFO, format='%(asctime)s | %(levelname)s | %(message)s')\nlog = logging.getLogger('genesis')\n\n@app.post('/webhook/pine')\nasync def receive_pine_alert(request: Request):\n    payload = await request.json()\n    log.info(f'📡 Pine Sensor: {json.dumps(payload)}')\n    return {'status': 'received', 'ts': datetime.utcnow().isoformat(), 'payload': payload}\n\n@app.get('/health')\nasync def health():\n    return {'status': 'ok', 'service': 'genesis-webhook'}\n\nif __name__ == '__main__':\n    uvicorn.run('main:app', host='0.0.0.0', port=FASTAPI_PORT, reload=False)\n",

"run_pipeline.py": "import sys, json\nfrom agents.graph import build_graph\nfrom core.config import DEFAULT_THESIS\n\ndef main():\n    thesis = DEFAULT_THESIS if len(sys.argv) < 2 else ' '.join(sys.argv[1:])\n    print(f'🔬 Iniciando R&D para: {thesis}')\n    app = build_graph()\n    result = app.invoke({'thesis': thesis, 'status': 'start'})\n    print('\\n📊 RESULTADO DA VALIDACAO:')\n    print(json.dumps(result, indent=2, ensure_ascii=False))\n\nif __name__ == '__main__':\n    main()\n"
}

for path, content in FILES.items():
    Path(path).write_text(content)
    print(f'✅ Criado: {path}')

print('\n🎉 PROJETO GENESIS 100% CRIADO. Pronto para git add & push.')
